### ISSUE TITLE
Docker安装langchat时，提示nginx.conf是个目录不是文件，无法启动成功，如何处理

### ISSUE THREAD

**Issue by wuchubuzai2018** [TyCoding/langchat#6]
使用docker compose up命令出现nginx错误
错误提示为：
error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/langchat/langchat-main/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /opt/langchat/langchat-main/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
docker脚本使用的是gitee上的：
https://gitee.com/TyCoding/langchat/blob/main/docker-compose.yml

**Comment by TyCoding** [comment]
脚本本身有问题，以github仓库为准，docker-compose部署脚本不再提供，又需要可以联系我商业部署支持
